name: Run pytest

on:
  push:
    branches:
      - '*'  # Change this to your default branch if it's not 'main'

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Specify the Python version you want to use (e.g., 3.8, 3.9)

    - name: Install dependencies
      run: |
        pip install -r ./code/requirements.txt

    - name: Run pytest
      run: |
        cd code
        pytest
