name: Handle file uploaded in issue 

on: 
  issues:
    types: [opened, edited]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue URL: ${{ github.event.issue.url }}"
      
      - name: Access Issue files
        uses: g-pst/opentools-issueprocessor@develop
        id: issue_branch
        with:
          issue_number: "${{ github.event.issue.number }}"
          issue_title: "${{ github.event.issue.title }}"
          issue_url: "${{ github.event.issue.url }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          datapath: data
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: steps.issue_branch.outputs.branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.issue_branch.outputs.branch }}
          title: 'Automated Pull Request'
          body: 'This pull request was automatically created.'