name: Validate Data
on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Validate data and test generating the site
        id: test
        uses: g-pst/opentools-builder@v3
        with:
          outputpath: ${{ env.GITHUB_OUTPUT }}

      # Post a comment then use the shell command 'test' without arguments to
      # return a non-zero exit code. A bit hacky, but we need to keep the job
      # running after the actual tests in order to report the results, so we
      # hold off on failing the job until here.
      - name: Check for failed data validation
        if: ${{ steps.test.outputs.status != 'pass' }}
        run: gh pr comment $PR --body-file errormessage.md; test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
