name: Validate Data
on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Validate data and test generating the site
        uses: g-pst/opentools-builder@v2
